meditation_design_task:
  description: >
    Design a complete {theme} meditation session lasting {duration} minutes.

    Requirements:
    - Create a therapeutic progression from opening to closing
    - Include appropriate segments based on the theme and duration
    - Design natural transitions between segments
    - Target {difficulty_level} practitioners
    - Incorporate both guidance and silence periods
    - Design appropriate breathing patterns

    Your design should include:
    - Overall session structure and flow
    - Segment breakdown with timing
    - Key elements to include
    - Breathing pattern recommendations
    - Silence placement
    - Music suggestions (if appropriate)

  expected_output: >
    A detailed meditation session plan following the MeditationStructure schema, including:
    - Session metadata (title, theme, difficulty, duration)
    - Segment breakdown with specific timing
    - Key elements and focus points
    - Breathing pattern specifications
    - Music recommendations if applicable

    Your output must be structured as a valid MeditationStructure object.
  agent: meditation_designer

content_creation_task:
  description: >
    Write all voice scripts and breathing instructions for the meditation session structure provided.

    Requirements:
    - Create soothing, clear voice instructions for each segment
    - Write in present tense with a warm, supportive tone
    - Include natural speech pacing and pauses
    - Craft guidance appropriate for {difficulty_level} level
    - Match the overall tone to the {theme} theme
    - Design breath guidance with appropriate cues

    For each segment, create:
    - Opening instructions
    - Main guidance text
    - Transition language
    - Breath cues (where applicable)
    - Closing words

  expected_output: >
    Complete meditation content following the MeditationContent schema, including:
    - Voice instructions for each segment with exact wording
    - Breath guidance with cues and timing
    - Silence period instructions
    - Transition language between segments

    Your output must follow the MeditationContent schema with detailed ScriptSegment objects.
  agent: content_creator

timing_orchestration_task:
  description: >
    Calculate precise timing for all meditation elements based on the session content.

    Requirements:
    - Calculate exact start and end times for each segment in seconds
    - Determine timing for all voice instructions
    - Create precise breathing pattern timing (inhale/exhale/hold/rest)
    - Plan silence durations and placement
    - Ensure smooth transitions between elements
    - Make sure the total duration is exactly {duration} minutes

    Consider:
    - Natural speaking pace (approximately 150 words per minute)
    - Comfortable breathing rhythms
    - Appropriate silence durations
    - Transition timing between segments
    - Coordination between multiple agents (voice, breath, timer, music)

  expected_output: >
    Precise timing specification formatted as a valid MeditationTiming object including:
    - Segment start/end times in seconds
    - Instruction timing for each agent
    - Breathing pattern timing and repetitions
    - Silence period timing
    - Music timing (if applicable)

    Your output must conform to the MeditationTiming schema with TimedSegment and TimedInstruction objects.
  agent: timing_specialist

session_formatting_task:
  description: >
    Convert the complete meditation session with content and timing into a structured JSON format for execution.

    Requirements:
    - Create a valid MeditationSession object following the schema exactly
    - Include all segments with precise start and end times
    - Define all agent actions with exact timing and parameters
    - Ensure all voice text is properly formatted
    - Include complete breath guidance parameters
    - Add timer silence periods
    - Include music instructions if applicable
    - Ensure total duration matches {duration} minutes exactly

    Agent actions to include:
    - VoiceAgent: speak, pause
    - BreathAgent: inhale_cue, exhale_cue, breathing_cycle
    - TimerAgent: silence, transition_cue, segment_timer
    - MusicAgent: play, fade_in, fade_out, volume_change

  expected_output: >
    A complete, valid MeditationSession object in JSON format that includes:
    - Session metadata (title, duration, theme, difficulty)
    - Segment definitions with timing
    - Agent action specifications
    - All parameters needed for execution

    The output JSON must conform exactly to the MeditationSession schema and be ready for direct execution by the frontend.
  agent: session_formatter
